id = "lmy"
name = "lmy"
description = "lmy"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lmy_zed"

[grammars.lmy]
repository = "https://github.com/orlaya/lmy_tree"
commit = "cb08758795e2bb7211d4ad9bb8fc3203a92ff7d3"
