id = "lmy"
name = "lmy"
description = "lmy"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lmy_zed"

[grammars.lmy]
repository = "https://github.com/orlaya/lmy_tree"
commit = "a9fcefa36e25ebbaa0e6cc45da8a63e63baa47c0"
