id = "lmy"
name = "lmy"
description = "lmy"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lmy_zed"

[grammars.lmy]
repository = "https://github.com/orlaya/lmy_tree"
commit = "3fedf807f45f2af12c2f10741329c3ff761bf076"
